language: perl
perl:
  - "5.8"
  - "5.14"
  - "5.20"
before_install:
  - echo 'yes' | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - curl -L https://github.com/jgm/cmark/archive/0.18.tar.gz | tar xz
  - cd cmark-0.18 && make && sudo make install
  - eval $(curl https://travis-perl.github.io/init) --auto

