language: perl
perl:
  - "5.8"
  - "5.14"
matrix:
  include:
    - perl: "5.20"
      env:
        - COVERAGE=1
before_install:
  - echo 'yes' | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - curl -L https://github.com/jgm/cmark/archive/0.18.1.tar.gz | tar xz
  - (cd cmark-0.18.1 && make && sudo make install && sudo ldconfig)
  - |
      helper_dir="$(mktemp -d -t travis-perl-helpers-XXXXXX)"
      git clone git://github.com/nwellnhof/travis-perl-helpers "$helper_dir"
      source "$helper_dir/init" --auto

