sudo: false
language: perl
perl:
  - "5.8"
  - "5.14"
matrix:
  include:
    - perl: "5.20"
      env:
        - COVERAGE=1 COVERAGE_OPTS='-ignore_re /CORE/\w+\.h$'
env:
  global:
    - CMARK_VERSION=0.21.0
    - CMARK_PREFIX="$TRAVIS_BUILD_DIR/cmark-$CMARK_VERSION/install"
    - LD_LIBRARY_PATH="$CMARK_PREFIX/lib"
    - PERL_MM_OPT="INC=-I$CMARK_PREFIX/include LIBS=-L$CMARK_PREFIX/lib\\ -lcmark"
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
before_install:
  - curl -L https://github.com/jgm/cmark/archive/$CMARK_VERSION.tar.gz | tar xz
  - (cd cmark-$CMARK_VERSION && make INSTALL_PREFIX="$CMARK_PREFIX" install)
  - |
      helper_dir="$(mktemp -d -t travis-perl-helpers-XXXXXX)"
      git clone git://github.com/nwellnhof/travis-perl-helpers "$helper_dir"
      source "$helper_dir/init" --auto

